//INTAKE LOAD
export const LOAD_ONE_NOTE = "LOAD_ONE_NOTE";
export const LOAD_ALL_NOTE = "LOAD_ALL_NOTE";
export const LOAD_COMPLETED_NOTE = "LOAD_COMPLETED_NOTE";
export const LOAD_INCOMPLETE_NOTE = "LOAD_INCOMPLETE_NOTE";

//INTAKE INSERT
export const UPDATE_ONE_NOTE = "UPDATE_ONE_NOTE";
export const BUILD_COMPLETED = "BUILD_COMPLETED";
export const BUILD_INCOMPLETE = "BUILD_INCOMPLETE";

//SYMPTOMS UPDATES
export const UPDATE_ONE_SYMPTOM = "UPDATE_ONE_SYMPTOM";

//UPDATE REVIEW
export const UPDATE_ONE_REVIEW_OPTIONS = "UPDATE_ONE_REVIEW_OPTIONS";
export const UPDATE_ONE_REVIEW_OTHER = "UPDATE_ONE_REVIEW_OTHER";
export const UPDATE_REVIEW_OPTIONS = "UPDATE_REVIEW_OPTIONS";
export const UPDATE_INTAKE_STATUS = "UPDATE_INTAKE_STATUS";
